### ISSUE TITLE
cdb mmaping

### ISSUE THREAD

**Issue by mrsndmn** [alldroll/cdb#5]
Hi!

CDB file mmapping could improve performance. I wouldn't recomend to use it with fat CDBs.

I benched it [here](https://github.com/mrsndmn/cdb/blob/benchmmap/cdb_test.go#L271) and got 7 times performance improvement on my laptop.
```
BenchmarkReaderGet-8          	  759301	      1397 ns/op
BenchmarkReaderGetMMaped-8    	 6424041	       194 ns/op
```

May be we should add this point to `README.md`?

mmapping is better than using of tmpfs because mmapped file reading does not requre any syscall

**Comment by alldroll** [comment]
Hi @mrsndmn 

File `mmap` definitely shows better performance. We use abstraction [io.ReaderAt](https://github.com/alldroll/cdb/blob/master/cdb.go#L95) and it is easy to replace `file` implementation with `mmap` [usage example](https://github.com/suggest-go/suggest/blob/dd353d3e1297ac79ed573563187fe4f156c4bcaa/pkg/dictionary/helpers.go#L15)

I think we can mention this fact in our README, let's say as `the best practice` or `performance tricks`.

Would you like to contribute?
